kind: pipeline
name: hugo build

steps:
- name: build
  image: cibuilds/hugo:0.73
  volumes:
  - name: output
    path: /static
  commands:
  - mkdir /tmp/src
  - cp -r * /tmp/src
  - hugo -d /tmp/static -s /tmp/src
  - htmlproofer /tmp/static --allow-hash-href --check-html --empty-alt-ignore --disable-external
  - sudo rm -rf /static/*
  - sudo cp -r /tmp/static/* /static
  - sudo chown -R 1000:1000 /static
  environment:
    HUGO_ENV: production

volumes:
- name: output
  host:
    path: /srv/static/blog.tdem.in
