kind: pipeline
name: hugo build

steps:
- name: build
  image: cibuilds/hugo
  volumes:
  - name: output
    path: /static
  commands:
  - rm -rf /static/*
  - hugo -d /static
  environment:
    HUGO_ENV: production

volumes:
- name: output
  host:
    path: /srv/static/blog.tdem.in
