baseURL = "https://blog.tdem.in/"
languageCode = "en-us"
title = "Timur Demin's Blog"
theme = "basics"

[markup.goldmark.renderer]
unsafe = true

[author]
name = "Timur Demin"
email = "me@tdem.in"

[params]
author = "Timur Demin"
email = "me@tdem.in"
description = "Random rants on technology, chess, and music"
home = "https://tdem.in"
