baseURL = "https://tdem.in/"
languageCode = "en-us"
title = "Timur Demin's Blog"
theme = "basics"

[markup.highlight]
codeFences = true
# guessSyntax = false
# hl_Lines = ""
# lineNoStart = 1
# lineNos = false
# lineNumbersInTable = true
# noClasses = true
style = "monokai"
# tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[author]
name = "Timur Demin"
email = "me@tdem.in"

[params]
description = "Random rants on technology, chess, and music"
home = "https://tdem.in"
sourceCode = "https://git.tdem.in/tdemin/blog.tdem.in"
tocEnabled = false
