name: Deploy to GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

env:
  hugo_version: 0.115.3

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Hugo
        run: |
          wget -qO- \
            https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_linux-amd64.tar.gz \
          | tar -x -z -v \
            -C /usr/local/bin \
            hugo
      - name: Build website with Hugo
        run: |
          mkdir -p ./hugo
          hugo -d ./hugo
        env:
          HUGO_ENV: production
      - name: Deploy to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo
          cname: tdem.in
